---
runtime:
  threads: ~
manifest:
  url: "https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml"
language: en-US
theme: light
roots:
  - path: "C:/Program Files (x86)/Steam"
    store: steam
  - path: "C:/Program Files (x86)/Epic Games"
    store: epic
  - path: "C:/Program Files/Epic Games"
    store: epic
  - path: "C:/GOG Games"
    store: gog
  - path: "C:/Program Files/WindowsApps"
    store: microsoft
  - path: "C:/Amazon Games/Library"
    store: prime
redirects: []
backup:
  path: ".\\ludusavi-backup"
  ignoredGames: []
  filter:
    excludeStoreScreenshots: false
    ignoredPaths: []
    ignoredRegistry: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: name
    reversed: false
  retention:
    full: 1
    differential: 0
  format:
    chosen: simple
    zip:
      compression: deflate
    compression:
      deflate:
        level: 6
      bzip2:
        level: 6
      zstd:
        level: 10
restore:
  path: ".\\ludusavi-backup"
  ignoredGames: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: name
    reversed: false
scan:
  showDeselectedGames: true
  showUnchangedGames: true
  showUnscannedGames: true
cloud:
  remote: ~
  path: ludusavi-backup
  synchronize: true
apps:
  rclone:
    path: ""
    arguments: ""
customGames: []
