# Imports
from joybox.bootstrap.installers.installer_aptget import *
from joybox.bootstrap.installers.installer_awscli import *
from joybox.bootstrap.installers.installer_audiobookshelf import *
from joybox.bootstrap.installers.installer_brave import *
from joybox.bootstrap.installers.installer_certbot import *
from joybox.bootstrap.installers.installer_cockpit import *
from joybox.bootstrap.installers.installer_chrome import *
from joybox.bootstrap.installers.installer_claude import *
from joybox.bootstrap.installers.installer_config import *
from joybox.bootstrap.installers.installer_dconf import *
from joybox.bootstrap.installers.installer_deno import *
from joybox.bootstrap.installers.installer_dockerapp import *
from joybox.bootstrap.installers.installer_dotfiles import *
from joybox.bootstrap.installers.installer_gh import *
from joybox.bootstrap.installers.installer_githooks import *
from joybox.bootstrap.installers.installer_filebrowser import *
from joybox.bootstrap.installers.installer_fitlog import *
from joybox.bootstrap.installers.installer_flatpak import *
from joybox.bootstrap.installers.installer_gitkraken import *
from joybox.bootstrap.installers.installer_jenkins import *
from joybox.bootstrap.installers.installer_kanboard import *
from joybox.bootstrap.installers.installer_llamacpp import *
from joybox.bootstrap.installers.installer_navidrome import *
from joybox.bootstrap.installers.installer_nginx import *
from joybox.bootstrap.installers.installer_node import *
from joybox.bootstrap.installers.installer_ollama import *
from joybox.bootstrap.installers.installer_oscar import *
from joybox.bootstrap.installers.installer_onepassword import *
from joybox.bootstrap.installers.installer_python import *
from joybox.bootstrap.installers.installer_sdl3 import *
from joybox.bootstrap.installers.installer_steam import *
from joybox.bootstrap.installers.installer_sysctl import *
from joybox.bootstrap.installers.installer_udev import *
from joybox.bootstrap.installers.installer_vale import *
from joybox.bootstrap.installers.installer_virtualbox import *
from joybox.bootstrap.installers.installer_vscodium import *
from joybox.bootstrap.installers.installer_wine import *
from joybox.bootstrap.installers.installer_winget import *
from joybox.bootstrap.installers.installer_wordpress import *
from joybox.bootstrap.installers.installer_wrappers import *
from joybox.bootstrap.installers.installer_xorg import *
from joybox.bootstrap.installers.installer import *
