# Imports
import os

# Local imports
import joybox.bootstrap.constants as constants
from joybox import settings
from . import installer
from joybox import runoptions
from joybox import logger

# Python wrapper template
PYTHON_WRAPPER_TEMPLATE = '''#!/bin/bash
# JoyBox python3 wrapper - uses venv python
# Generated by JoyBox Bootstrap
exec "{venv_python}" "$@"
'''

# Pip wrapper template
PIP_WRAPPER_TEMPLATE = '''#!/bin/bash
# JoyBox pip3 wrapper - uses venv pip
# Generated by JoyBox Bootstrap
exec "{venv_pip}" "$@"
'''

# Marker file for tracking installation
MARKER_FILE = ".joybox_wrappers_installed"

# The wrappers this component makes. The JoyBox commands themselves are
# installed into the venv by pip, from the package's [project.scripts].
WRAPPER_NAMES = ["python3", "pip3"]

# Wrappers
class Wrappers(installer.Installer):
    def __init__(
        self,
        connection,
        flags = runoptions.RunFlags(),
        options = runoptions.RunOptions()):
        super().__init__(connection, flags, options)

        # Paths
        self.local_bin_dir = os.path.expandvars("$HOME/.joybox/bin")
        self.marker_path = f"{self.local_bin_dir}/{MARKER_FILE}"

        # Get venv paths
        python_venv_dir = settings.get_value("Tools.Python", "python_venv_dir")
        venv_bin_dir = os.path.join(os.path.expandvars(python_venv_dir or "$HOME/.venv"), "bin")
        self.venv_python = os.path.join(venv_bin_dir, "python3")
        self.venv_pip = os.path.join(venv_bin_dir, "pip3")

    def get_supported_environments(self):
        return [
            constants.EnvironmentType.LOCAL_UBUNTU,
        ]

    def get_recorded_wrappers(self):
        if not self.connection.does_file_or_directory_exist(self.marker_path):
            return []
        return [name for name in (self.connection.read_file(self.marker_path) or "").split("\n") if name]

    def is_installed(self):
        return sorted(self.get_recorded_wrappers()) == sorted(WRAPPER_NAMES)

    def install(self):

        # Start install
        logger.log_info("Installing JoyBox python wrappers")
        if not self.connection.does_file_or_directory_exist(self.venv_python):
            logger.log_error(f"No virtual environment python at {self.venv_python}; install the python component first")
            return False

        # Remove script wrappers left from before the commands were installed by pip
        for name in self.get_recorded_wrappers():
            if name not in WRAPPER_NAMES:
                logger.log_info(f"Removing old script wrapper: {name}")
                self.connection.remove_file_or_directory(f"{self.local_bin_dir}/{name}")

        # Write wrappers
        self.connection.make_directory(self.local_bin_dir)
        contents = {
            "python3": PYTHON_WRAPPER_TEMPLATE.format(venv_python = self.venv_python),
            "pip3": PIP_WRAPPER_TEMPLATE.format(venv_pip = self.venv_pip),
        }
        for name in WRAPPER_NAMES:
            wrapper_path = f"{self.local_bin_dir}/{name}"
            logger.log_info(f"Creating wrapper: {name}")
            if not self.connection.write_file(wrapper_path, contents[name]):
                return False
            self.connection.change_permission(wrapper_path, "755")

        # Record what was installed
        return self.connection.write_file(self.marker_path, "\n".join(WRAPPER_NAMES))

    def uninstall(self):

        # Start uninstall
        logger.log_info("Uninstalling JoyBox wrappers")
        for name in self.get_recorded_wrappers():
            logger.log_info(f"Removing wrapper: {name}")
            self.connection.remove_file_or_directory(f"{self.local_bin_dir}/{name}")
        self.connection.remove_file_or_directory(self.marker_path)
        return True

    def get_package_status(self):
        recorded = self.get_recorded_wrappers()
        return {
            "installed": [name for name in WRAPPER_NAMES if name in recorded],
            "missing": [name for name in WRAPPER_NAMES if name not in recorded]
        }
