# Imports
import os
import sys
import copy
import configparser

# Local imports
import util
import settings

# Config file header
CONFIG_HEADER = """; ============================================================
; JoyBox Configuration File
; Generated by JoyBox Bootstrap
; ============================================================

"""

def generate_default_config_content(sections = None):
    sections_to_include = sections if sections else list(settings.ini_defaults.keys())
    content = CONFIG_HEADER
    for section_name in sections_to_include:
        if section_name not in settings.ini_defaults:
            continue
        content += f"[{section_name}]\n"
        for key, value in settings.ini_defaults[section_name].items():
            if str(value) == "":
                content += f"; {key} = \n"
            else:
                content += f"{key} = {value}\n"
        content += "\n"
    return content

def create_default_config_file(path, sections = None):
    config_dir = os.path.dirname(path)
    if config_dir:
        os.makedirs(config_dir, exist_ok = True)
    with open(path, "w") as f:
        f.write(generate_default_config_content(sections))

class Configuration:
    def __init__(self, src, default_config = None):

        # Check for default config
        if not default_config:
            default_config = {}

        # Load current config if it exists
        self.config = self.read_from_file(src) if os.path.isfile(src) else {}

        # Add in the default config sections
        updated = False
        for section, defaults in default_config.items():
            if section not in self.config:
                self.config[section] = {}
            if not self.has_section(section):
                self.add_section(section)
            for key, default_value in defaults.items():
                if key not in self.config[section]:
                    self.config[section][key] = util.prompt_for_value(key, default_value)
                    updated = True
                self.set_value(section, key, str(self.config[section][key]))

        # Write config back to file
        if updated or not os.path.isfile(src):
            self.Write(src)

    def copy(self):
        return copy.deepcopy(self)

    def read_from_file(self, src):
        try:
            result = {}
            self.parser = configparser.ConfigParser(interpolation = None)
            self.parser.read(src)
            for section in self.parser.sections():
                section_dict = {}
                for key, value in self.parser.items(section):
                    if value.lower() in ["true", "false"]:
                        section_dict[key] = self.parser.getboolean(section, key)
                    else:
                        section_dict[key] = value
                result[section] = section_dict
            return result
        except Exception as e:
            util.log_error(f"Error reading the config file '{src}'")
            util.log_error(e)
            return None

    def write_to_file(self, src):
        try:
            self.parser = configparser.ConfigParser(interpolation=None)
            for section, items in self.config.items():
                if not self.parser.has_section(section):
                    self.parser.add_section(section)
                for key, value in items.items():
                    self.parser.set(section, key, str(value))
            with open(src, "w") as f:
                self.parser.write(f)
            return True
        except Exception as e:
            util.log_error(f"Error writing the config file '{src}'")
            util.log_error(e)
            return False

    def has_section(self, section):
        return section in self.config

    def add_section(self, section):
        if self.has_section(section):
            self.config[section] = {}

    def set_value(self, section, key, value):
        if not self.has_section(section):
            self.config[section] = {}
        self.config[section][key] = value

    def get_value(self, section, key, default_value = None):
        return self.config.get(section, {}).get(key, default_value)
