# Imports
import os
import os.path
import sys
import json
import subprocess
import tempfile
import textwrap
import tomllib

# Local imports
import joybox.default_settings as default_settings

# Header on every generated page
GENERATED_NOTICE = "<!-- Generated by build_man_pages from %s. Edit its help text, not this file. -->"

# The package every command lives in
COMMAND_PACKAGE = "joybox.cli"

# Title of the ungrouped options
DEFAULT_GROUP_TITLE = "General"

# Section for a tool that does not name one
DEFAULT_SECTION = "Other"

# Column prose is wrapped at, matching the repo's markdownlint line length
PAGE_WIDTH = 100

# The only environment a described script sees. Defaults can be read from the
# environment, and a token set in the shell must not end up on a page.
PASSED_ENVIRONMENT = ["PATH", "LANG", "LC_ALL", "SYSTEMROOT", "TEMP", "TMP"]

# Builds a command's parser and writes its description. The command module is
# imported, never run, and nothing is parsed.
PROBE_SOURCE = """
import importlib, json, sys
module_name, output_path = sys.argv[1], sys.argv[2]
parser = importlib.import_module(module_name).build_parser()
with open(output_path, "w") as output_file:
    json.dump(parser.describe(), output_file)
"""

# Get the commands a pyproject.toml declares, as (command, module) pairs
def find_commands(pyproject_path):
    with open(pyproject_path, "rb") as pyproject_file:
        scripts = tomllib.load(pyproject_file).get("project", {}).get("scripts", {})
    found = []
    for command, target in sorted(scripts.items()):
        module_name = target.split(":", 1)[0]
        if module_name.startswith(COMMAND_PACKAGE + "."):
            found.append((command, module_name))
    return found

# Get the source file a command module was generated from, relative to the repo
def get_module_source(module_name):
    return "Shared/%s.py" % module_name.replace(".", "/")

# Describe a command's parser, run against a home directory holding only the
# default JoyBox.ini so nothing from the local one leaks into the documentation
def describe_command(module_name, python_path, timeout = 60):
    with tempfile.TemporaryDirectory() as home_dir:
        default_settings.create_default_config_file(os.path.join(home_dir, "JoyBox.ini"))
        output_path = os.path.join(home_dir, "parser.json")
        env = {name: os.environ[name] for name in PASSED_ENVIRONMENT if name in os.environ}
        env["HOME"] = home_dir
        env["USERPROFILE"] = home_dir
        env["PYTHONPATH"] = os.pathsep.join(python_path)
        result = subprocess.run(
            [sys.executable, "-c", PROBE_SOURCE, module_name, output_path],
            check = False,
            capture_output = True,
            text = True,
            timeout = timeout,
            cwd = home_dir,
            env = env)
        if not os.path.exists(output_path):
            raise RuntimeError("Unable to describe %s: %s" % (module_name, result.stderr.strip()[-2000:]))
        with open(output_path, "r") as output_file:
            spec = json.load(output_file)
    spec = replace_home_in_defaults(spec, home_dir)
    spec["module"] = module_name
    return spec

# Swap the throwaway home directory for ~ in any default derived from it
def replace_home_in_defaults(spec, home_dir):
    def replace(value):
        if isinstance(value, str):
            return value.replace(home_dir, "~")
        if isinstance(value, list):
            return [replace(item) for item in value]
        return value
    for group in spec["groups"]:
        for option in group["options"]:
            option["default"] = replace(option["default"])
    return spec

#################################################

# Find what is missing from a tool's help text
def find_help_problems(tool_name, spec, known_tools):
    problems = []
    if not (spec.get("description") or "").strip():
        problems.append("no description")
    if not spec.get("section"):
        problems.append("no section")
    for group in spec["groups"]:
        for option in group["options"]:
            if not (option.get("description") or "").strip():
                problems.append("no help text for %s" % format_flags(option))
    if not spec.get("examples"):
        problems.append("no examples")
    for title, command in spec.get("examples", []):
        if not title.strip():
            problems.append("an example has no title")
        if not command.startswith(tool_name):
            problems.append("example does not run %s: %s" % (tool_name, command))
    for other in spec.get("see_also", []):
        if other == tool_name:
            problems.append("see_also names itself")
        elif other not in known_tools:
            problems.append("see_also names an unknown tool: %s" % other)
    return problems

#################################################

# Get an option's flags as they were declared
def format_flags(option):
    if option["positional"]:
        return "<%s>" % option["dest"]
    return ", ".join(option["flags"])

# Get an option's placeholder value
def format_value(option):
    if option["positional"] or not option["takes_value"]:
        return ""
    if option["choices"]:
        return " <%s>" % "|".join(option["choices"]) if len(option["choices"]) <= 4 else " <%s>" % option["dest"]
    return " <%s>" % option["dest"]

# Get an option's cell in the options table
def format_option_cell(option):
    return ("`%s%s`" % (format_flags(option), format_value(option))).replace("|", "\\|")

# Get an option's description cell, with its default and allowed values
def format_description_cell(option):
    text = option["description"].strip().rstrip(".")
    parts = [text + "."]
    if option["required"] and not option["positional"]:
        parts.append("**Required.**")
    default = option["default"]
    if default not in (None, False, [], ""):
        if isinstance(default, list):
            default = ",".join(str(value) for value in default)
        parts.append("Default: `%s`." % default)
    if option["choices"]:
        parts.append("Allowed: %s." % ", ".join("`%s`" % choice for choice in option["choices"]))
    return " ".join(parts).replace("|", "\\|").replace("\n", " ")

# Get the synopsis line
def format_synopsis(tool_name, spec):
    words = [tool_name]
    for group in spec["groups"]:
        for option in group["options"]:
            if option["positional"]:
                words.append("<%s>" % option["dest"])
            elif option["required"]:
                words.append("%s%s" % (option["flags"][0], format_value(option)))
    words.append("[options]")
    return " ".join(words)

#################################################

# Format a list item, wrapped with its continuation lines under the text
def format_bullet(text):
    return textwrap.fill(
        text,
        width = PAGE_WIDTH,
        initial_indent = "- ",
        subsequent_indent = "  ",
        break_long_words = False,
        break_on_hyphens = False)

# Render a tool's man page
def render_page(tool_name, spec, descriptions = None):
    descriptions = descriptions or {}
    lines = [
        GENERATED_NOTICE % get_module_source(spec.get("module") or "%s.%s" % (COMMAND_PACKAGE, tool_name)),
        "",
        "# %s" % tool_name,
        "",
        "[← Command index](README.md)",
        "",
        textwrap.fill(spec["description"].strip(), width = PAGE_WIDTH, break_long_words = False, break_on_hyphens = False),
        "",
        "## Synopsis",
        "",
        "```text",
        format_synopsis(tool_name, spec),
        "```",
        "",
    ]
    if spec.get("details"):
        lines += ["## Description", "", spec["details"].strip(), ""]
    lines += ["## Options", ""]
    for group in spec["groups"]:
        lines += [
            "### %s" % (group["title"] or DEFAULT_GROUP_TITLE),
            "",
            "| Option | Description |",
            "|--------|-------------|",
        ]
        for option in group["options"]:
            lines.append("| %s | %s |" % (format_option_cell(option), format_description_cell(option)))
        lines.append("")
    if spec.get("examples"):
        lines += ["## Examples", ""]
        for title, command in spec["examples"]:
            lines += ["### %s" % title, "", "```bash", command, "```", ""]
    if spec.get("notes"):
        lines += ["## Notes", ""]
        lines += [format_bullet(note) for note in spec["notes"]]
        lines.append("")
    if spec.get("see_also"):
        lines += ["## See also", ""]
        for other in spec["see_also"]:
            summary = descriptions.get(other)
            lines.append(format_bullet("[%s](%s.md)%s" % (other, other, " — %s" % summary if summary else "")))
        lines.append("")
    return "\n".join(lines)

# Render the index of every tool, grouped by section
def render_index(specs):
    sections = {}
    for tool_name, spec in specs.items():
        sections.setdefault(spec.get("section") or DEFAULT_SECTION, []).append(tool_name)
    lines = [
        "<!-- Generated by build_man_pages. Edit the scripts' help text, not this file. -->",
        "",
        "# Command Reference",
        "",
        "[← Docs index](../../README.md)",
        "",
        "One page per JoyBox command, generated from its `--help`. Every page is also",
        "available in the terminal as `<command> -h`.",
        "",
    ]
    for section in sorted(sections, key = lambda name: (name == DEFAULT_SECTION, name)):
        lines += ["## %s" % section, "", "| Command | Description |", "|---------|-------------|"]
        for tool_name in sorted(sections[section]):
            summary = specs[tool_name]["description"].strip().replace("|", "\\|")
            lines.append("| [%s](%s.md) | %s |" % (tool_name, tool_name, summary))
        lines.append("")
    return "\n".join(lines)

# Render every page, keyed by file name
def render_all(specs):
    descriptions = {name: spec["description"].strip().rstrip(".") for name, spec in specs.items()}
    pages = {"README.md": render_index(specs)}
    for tool_name, spec in specs.items():
        pages["%s.md" % tool_name] = render_page(tool_name, spec, descriptions)
    return pages

#################################################

# Describe every command a pyproject.toml declares
def describe_commands(pyproject_path, python_path):
    return {command: describe_command(module_name, python_path) for command, module_name in find_commands(pyproject_path)}

# Get the pages that differ from what is on disk, and the files that would be removed
def find_stale_pages(pages, output_dir):
    stale = []
    for filename, content in pages.items():
        path = os.path.join(output_dir, filename)
        if not os.path.exists(path):
            stale.append(filename)
            continue
        with open(path, "r") as page_file:
            if page_file.read() != content:
                stale.append(filename)
    extra = []
    if os.path.isdir(output_dir):
        extra = sorted(name for name in os.listdir(output_dir) if name.endswith(".md") and name not in pages)
    return stale, extra

# Write every page, removing pages for tools that no longer exist
def write_pages(pages, output_dir):
    os.makedirs(output_dir, exist_ok = True)
    stale, extra = find_stale_pages(pages, output_dir)
    for filename in stale:
        with open(os.path.join(output_dir, filename), "w") as page_file:
            page_file.write(pages[filename])
    for filename in extra:
        os.remove(os.path.join(output_dir, filename))
    return stale, extra
