---
manifest:
  url: "https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml"
  etag: "\"d29ff4d0e1bf02bab0b2abc4f3d92e6225b58a3b9c7d2e1a45f18762722c43e3\""
language: en-US
theme: light
roots: []
backup:
  path: ".\\ludusavi-backup"
  ignoredGames: []
  recentGames: []
  merge: false
  filter:
    ignoredPaths: []
    ignoredRegistry: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: name
    reversed: false
  retention:
    full: 1
    differential: 0
  format:
    chosen: simple
    zip:
      compression: deflate
restore:
  path: ".\\ludusavi-backup"
  ignoredGames: []
  recentGames: []
  redirects: []
  sort:
    key: name
    reversed: false
customGames: []
