# Imports
from installers.installer_aptget import *
from installers.installer_audiobookshelf import *
from installers.installer_brave import *
from installers.installer_certbot import *
from installers.installer_cockpit import *
from installers.installer_chrome import *
from installers.installer_config import *
from installers.installer_dotfiles import *
from installers.installer_ghidra import *
from installers.installer_filebrowser import *
from installers.installer_flatpak import *
from installers.installer_gitkraken import *
from installers.installer_jenkins import *
from installers.installer_kanboard import *
from installers.installer_navidrome import *
from installers.installer_nginx import *
from installers.installer_onepassword import *
from installers.installer_python import *
from installers.installer_vscodium import *
from installers.installer_wine import *
from installers.installer_winget import *
from installers.installer_wordpress import *
from installers.installer_wrappers import *
from installers.installer import *
