# Imports
import os
import sys

# Local imports
import util
import constants
import settings
from . import installer

# Config template header
CONFIG_HEADER = """; ============================================================
; JoyBox Configuration File
; Generated by JoyBox Bootstrap
; ============================================================

"""

# Config
class Config(installer.Installer):
    def __init__(
        self,
        config,
        connection,
        flags = util.RunFlags(),
        options = util.RunOptions()):
        super().__init__(config, connection, flags, options)

        # Path to config file
        self.config_path = os.path.expandvars("$HOME/JoyBox.ini")

        # Minimal sections to include by default
        self.minimal_sections = [
            "UserData.Dirs",
            "UserData.Protection",
            "Tools.Python",
            "Tools.Git",
        ]

    def get_supported_environments(self):
        return [
            constants.EnvironmentType.LOCAL_UBUNTU,
            constants.EnvironmentType.LOCAL_WINDOWS,
            constants.EnvironmentType.REMOTE_UBUNTU,
            constants.EnvironmentType.REMOTE_WINDOWS,
        ]

    def is_installed(self):
        return self.connection.does_file_or_directory_exist(self.config_path)

    def _generate_config_content(self, sections=None, full=False):
        content = CONFIG_HEADER
        if full:
            sections_to_include = list(settings.ini_defaults.keys())
        elif sections:
            sections_to_include = sections
        else:
            sections_to_include = self.minimal_sections
        for section_name in sections_to_include:
            if section_name not in settings.ini_defaults:
                continue
            content += f"[{section_name}]\n"
            section_defaults = settings.ini_defaults[section_name]
            for key, value in section_defaults.items():
                if value == "":
                    content += f"; {key} = \n"
                else:
                    content += f"{key} = {value}\n"
            content += "\n"
        return content

    def install(self):

        # Start install
        util.log_info("Installing JoyBox configuration file")

        # Check if config already exists
        if self.connection.does_file_or_directory_exist(self.config_path):
            util.log_info("JoyBox.ini already exists, skipping (will not overwrite)")
            return True

        # Generate config content (minimal by default)
        util.log_info("Generating minimal JoyBox.ini template")
        config_content = self._generate_config_content(full=False)

        # Write config file
        util.log_info(f"Writing {self.config_path}")
        if self.connection.write_file(self.config_path, config_content):
            util.log_info("JoyBox.ini created successfully")
            util.log_info("Edit ~/JoyBox.ini to configure your installation")
            return True

        # Configuration failed
        util.log_info("Configuration file installation failed")
        return False

    def install_full(self):

        # Start install
        util.log_info("Installing full JoyBox configuration file")

        # Check if config already exists
        if self.connection.does_file_or_directory_exist(self.config_path):
            util.log_info("JoyBox.ini already exists, skipping")
            return True

        # Generate config content
        config_content = self._generate_config_content(full=True)
        if self.connection.write_file(self.config_path, config_content):
            util.log_info("Full JoyBox.ini created successfully")
            return True

        # Configuration failed
        util.log_info("Configuration file installation failed")
        return False

    def uninstall(self):

        # Start uninstall
        util.log_info("Uninstalling JoyBox configuration file")

        # Backup before removing
        if self.connection.does_file_or_directory_exist(self.config_path):
            backup_path = os.path.expandvars("$HOME/JoyBox.ini.backup")
            util.log_info(f"Backing up to {backup_path}")
            self.connection.copy_file_or_directory(self.config_path, backup_path)
            self.connection.remove_file_or_directory(self.config_path)

        # All done
        util.log_info("Configuration file uninstallation complete")
        return True
