# Imports
import os
import sys

# Local imports
import util
import constants
from . import installer

# Wrapper template
WRAPPER_TEMPLATE = '''#!/bin/bash
# JoyBox wrapper for {script_name}
# Generated by JoyBox Bootstrap
exec "{python_path}" "{script_path}" "$@"
'''

# Python wrapper template
PYTHON_WRAPPER_TEMPLATE = '''#!/bin/bash
# JoyBox python3 wrapper - uses venv python
# Generated by JoyBox Bootstrap
exec "{venv_python}" "$@"
'''

# Marker file for tracking installation
MARKER_FILE = ".joybox_wrappers_installed"

# Wrappers
class Wrappers(installer.Installer):
    def __init__(
        self,
        config,
        connection,
        flags = util.RunFlags(),
        options = util.RunOptions()):
        super().__init__(config, connection, flags, options)

        # Paths
        self.local_bin_dir = os.path.expandvars("$HOME/.local/bin")
        self.marker_path = f"{self.local_bin_dir}/{MARKER_FILE}"

        # Get scripts directory from config
        scripts_dir = self.config.get_value("UserData.Dirs", "scripts_dir")
        if scripts_dir:
            self.scripts_bin_dir = os.path.join(scripts_dir, "bin")
        else:
            self.scripts_bin_dir = os.path.expandvars("$HOME/Repositories/JoyBox/Scripts/bin")

        # Get Python path - prefer venv if it exists, otherwise use system python
        python_venv_dir = self.config.get_value("Tools.Python", "python_venv_dir")
        if python_venv_dir:
            self.venv_python = os.path.expandvars(os.path.join(python_venv_dir, "bin", "python3"))
        else:
            self.venv_python = os.path.expandvars("$HOME/.venv/bin/python3")

        # Check if venv exists
        self.venv_exists = os.path.exists(self.venv_python)
        self.python_path = self.venv_python if self.venv_exists else "/usr/bin/python3"

    def get_supported_environments(self):
        return [
            constants.EnvironmentType.LOCAL_UBUNTU,
            constants.EnvironmentType.REMOTE_UBUNTU,
        ]

    def is_installed(self):
        return self.connection.does_file_or_directory_exist(self.marker_path)

    def _discover_scripts(self):
        expanded_dir = os.path.expandvars(self.scripts_bin_dir)
        scripts = []
        if os.path.isdir(expanded_dir):
            for entry in os.listdir(expanded_dir):
                if entry.endswith(".py"):
                    script_name = entry[:-3]  # Remove .py extension
                    script_path = os.path.join(expanded_dir, entry)
                    scripts.append((script_name, script_path))
        return sorted(scripts)

    def _generate_wrapper(self, script_name, script_path):
        return WRAPPER_TEMPLATE.format(
            script_name=script_name,
            python_path=os.path.expandvars(self.python_path),
            script_path=script_path
        )

    def install(self):

        # Start install
        util.log_info("Installing JoyBox script wrappers")

        # Create ~/.local/bin directory
        util.log_info("Creating ~/.local/bin directory")
        self.connection.make_directory(self.local_bin_dir)

        # Discover scripts
        scripts = self._discover_scripts()
        if not scripts:
            util.log_warning("No scripts found in Scripts/bin/")
            return False
        util.log_info(f"Found {len(scripts)} scripts to wrap")

        # Generate and install wrappers
        installed_wrappers = []
        for script_name, script_path in scripts:
            wrapper_content = self._generate_wrapper(script_name, script_path)
            wrapper_path = f"{self.local_bin_dir}/{script_name}"
            util.log_info(f"Creating wrapper: {script_name}")

            # Write wrapper to temp location first
            temp_path = f"/tmp/{script_name}_wrapper"
            if self.connection.write_file(temp_path, wrapper_content):
                self.connection.move_file_or_directory(temp_path, wrapper_path)
                self.connection.change_permission(wrapper_path, "755")
                installed_wrappers.append(script_name)

        # Create python3 wrapper if venv exists
        if self.venv_exists:
            util.log_info("Creating python3 wrapper pointing to venv")
            python_wrapper_content = PYTHON_WRAPPER_TEMPLATE.format(venv_python=self.venv_python)
            python_wrapper_path = f"{self.local_bin_dir}/python3"
            temp_path = "/tmp/python3_wrapper"
            if self.connection.write_file(temp_path, python_wrapper_content):
                self.connection.move_file_or_directory(temp_path, python_wrapper_path)
                self.connection.change_permission(python_wrapper_path, "755")
                installed_wrappers.append("python3")

        # Create marker file with list of installed wrappers
        marker_content = "\n".join(installed_wrappers)
        self.connection.write_file(self.marker_path, marker_content)

        # All done
        util.log_info(f"Installed {len(installed_wrappers)} wrappers to ~/.local/bin/")
        util.log_info("Ensure PATH includes ~/.local/bin (handled by dotfiles component)")
        return True

    def uninstall(self):

        # Start uninstall
        util.log_info("Uninstalling JoyBox script wrappers")

        # Read marker file to get list of installed wrappers
        if self.connection.does_file_or_directory_exist(self.marker_path):
            marker_content = self.connection.read_file(self.marker_path)
            if marker_content:
                wrappers = marker_content.strip().split("\n")
                for wrapper_name in wrappers:
                    wrapper_path = f"{self.local_bin_dir}/{wrapper_name}"
                    util.log_info(f"Removing wrapper: {wrapper_name}")
                    self.connection.remove_file_or_directory(wrapper_path)

        # Remove marker file
        self.connection.remove_file_or_directory(self.marker_path)

        # All done
        util.log_info("Wrapper uninstallation complete")
        return True

    def get_package_status(self):
        scripts = self._discover_scripts()
        installed = []
        missing = []
        for script_name, _ in scripts:
            wrapper_path = f"{self.local_bin_dir}/{script_name}"
            if self.connection.does_file_or_directory_exist(wrapper_path):
                installed.append(script_name)
            else:
                missing.append(script_name)
        return {
            "installed": installed,
            "missing": missing
        }
