# Imports
import os

# Third-party imports
import pytest

# Local imports
from joybox import manpage


###########################################################
# Helpers
###########################################################

def option(dest, flags = None, description = "Does a thing", **overrides):
    described = {
        "flags": flags if flags is not None else ["--%s" % dest],
        "dest": dest,
        "positional": False,
        "takes_value": True,
        "required": False,
        "description": description,
        "default": None,
        "choices": None,
    }
    described.update(overrides)
    return described


def spec(options = None, **overrides):
    described = {
        "description": "Do the thing.",
        "details": None,
        "examples": [["Run it", "tool --name x"]],
        "notes": [],
        "see_also": [],
        "section": "Things",
        "groups": [{"title": None, "options": options if options is not None else [option("name")]}],
    }
    described.update(overrides)
    return described


###########################################################
# Help problems
#
# These are what make the help text the documentation: a tool that fails any
# of them produces a page that leaves something out.
###########################################################

def test_complete_help_has_no_problems():
    assert manpage.find_help_problems("tool", spec(), ["tool"]) == []


@pytest.mark.parametrize("overrides,expected", [
    ({"description": " "}, "no description"),
    ({"section": None}, "no section"),
    ({"examples": []}, "no examples"),
    ({"examples": [["", "tool"]]}, "an example has no title"),
    ({"examples": [["Run it", "other --name x"]]}, "example does not run tool: other --name x"),
    ({"see_also": ["tool"]}, "see_also names itself"),
    ({"see_also": ["missing"]}, "see_also names an unknown tool: missing"),
])
def test_each_gap_is_reported(overrides, expected):
    assert expected in manpage.find_help_problems("tool", spec(**overrides), ["tool"])


def test_an_option_without_help_is_reported_by_its_flags():
    problems = manpage.find_help_problems("tool", spec([option("name", ["-n", "--name"], description = None)]), ["tool"])

    assert problems == ["no help text for -n, --name"]


###########################################################
# Rendering
###########################################################

def test_the_synopsis_lists_required_options_and_positionals():
    options = [
        option("source", ["source"], positional = True, required = True),
        option("name", ["-n", "--name"], required = True),
        option("verbose", ["-v"], takes_value = False),
    ]

    assert manpage.format_synopsis("tool", spec(options)) == "tool <source> -n <name> [options]"


def test_a_short_choice_list_becomes_the_placeholder():
    assert manpage.format_value(option("mode", choices = ["Tree", "Local"])) == " <Tree|Local>"


def test_a_long_choice_list_keeps_the_name_as_placeholder():
    assert manpage.format_value(option("mode", choices = list("abcde"))) == " <mode>"


def test_pipes_are_escaped_inside_the_options_table():
    page = manpage.render_page("tool", spec([option("mode", ["-m"], choices = ["Tree", "Local"])]))

    assert "`-m <Tree\\|Local>`" in page
    assert "Allowed: `Tree`, `Local`." in page


def test_the_default_is_shown_only_when_there_is_one():
    page = manpage.render_page("tool", spec([option("name", default = "x"), option("other")]))

    assert "Default: `x`." in page
    assert page.count("Default:") == 1


def test_a_required_option_is_marked():
    page = manpage.render_page("tool", spec([option("name", required = True)]))

    assert "**Required.**" in page


def test_ungrouped_options_get_the_general_heading():
    assert "### General" in manpage.render_page("tool", spec())


def test_see_also_links_carry_the_other_tools_summary():
    page = manpage.render_page("tool", spec(see_also = ["other"]), {"other": "Do the other thing"})

    assert "- [other](other.md) — Do the other thing" in page


def test_the_page_says_it_is_generated():
    assert manpage.render_page("tool", spec()).startswith("<!-- Generated by build_man_pages from Scripts/bin/tool.py.")


def test_the_index_groups_tools_by_section():
    index = manpage.render_index({"b": spec(section = "Beta"), "a": spec(section = "Alpha"), "c": spec(section = None)})

    headings = [line for line in index.splitlines() if line.startswith("## ")]

    assert headings == ["## Alpha", "## Beta", "## Other"]


def test_render_all_adds_the_index():
    assert set(manpage.render_all({"tool": spec()})) == {"README.md", "tool.md"}


###########################################################
# Defaults
###########################################################

def test_the_throwaway_home_becomes_a_tilde():
    described = spec([option("path", default = "/tmp/abc/Locker"), option("list", default = ["/tmp/abc/x", 3])])

    manpage.replace_home_in_defaults(described, "/tmp/abc")

    assert [o["default"] for o in described["groups"][0]["options"]] == ["~/Locker", ["~/x", 3]]


###########################################################
# Writing
###########################################################

def test_only_changed_pages_are_written_and_orphans_removed(tmp_path):
    (tmp_path / "same.md").write_text("same")
    (tmp_path / "old.md").write_text("old")
    (tmp_path / "gone.md").write_text("gone")

    stale, extra = manpage.write_pages({"same.md": "same", "old.md": "new", "added.md": "added"}, str(tmp_path))

    assert (sorted(stale), extra) == (["added.md", "old.md"], ["gone.md"])
    assert sorted(os.listdir(tmp_path)) == ["added.md", "old.md", "same.md"]
    assert (tmp_path / "old.md").read_text() == "new"


def test_checking_writes_nothing(tmp_path):
    stale, extra = manpage.find_stale_pages({"new.md": "new"}, str(tmp_path))

    assert (stale, extra, os.listdir(tmp_path)) == (["new.md"], [], [])


###########################################################
# Describing
###########################################################

def test_a_described_script_does_not_see_the_callers_environment(tmp_path, shared_dir, monkeypatch):
    # A default read from the environment would put a token on a public page.
    monkeypatch.setenv("JOYBOX_TEST_SECRET", "hunter2")
    script = tmp_path / "tool.py"
    script.write_text(
        "import os\n"
        "import joybox.arguments as arguments\n"
        "parser = arguments.ArgumentParser(description = 'Tool')\n"
        "parser.add_string_argument(args = ('-k', '--key'), default = os.environ.get('JOYBOX_TEST_SECRET'), description = 'Key')\n"
        "args, unknown = parser.parse_known_args()\n")

    described = manpage.describe_script(str(script), shared_dir)

    assert described["groups"][0]["options"][0]["default"] is None
