# Third-party imports
import pytest

# Local imports
from joybox import textblock


###########################################################
# Managed blocks
#
# Generated content bracketed by markers inside a file the user also owns.
# Replacing it must leave everything outside the markers exactly as it was,
# and running the same update twice must change nothing.
###########################################################

BEGIN = "# >>> JOYBOX MANAGED BLOCK >>>"
END = "# <<< JOYBOX MANAGED BLOCK <<<"
NOTE = "# Generated by JoyBox. Edits inside this block are overwritten."


def block_of(contents):
    return textblock.read_block_body(contents, BEGIN, END, NOTE)


###########################################################
# Finding
###########################################################

def test_a_block_is_found():
    contents = "before\n%s\nbody\n%s\nafter\n" % (BEGIN, END)

    assert textblock.has_block(contents, BEGIN, END) is True


def test_a_file_without_markers_has_no_block():
    assert textblock.has_block("just some content\n", BEGIN, END) is False


def test_a_begin_without_an_end_is_not_a_block():
    # A half written block should not be treated as one and silently eaten.
    assert textblock.has_block("%s\nbody\n" % BEGIN, BEGIN, END) is False


def test_an_end_without_a_begin_is_not_a_block():
    assert textblock.has_block("body\n%s\n" % END, BEGIN, END) is False


def test_an_end_before_a_begin_is_not_a_block():
    assert textblock.has_block("%s\n%s\n" % (END, BEGIN), BEGIN, END) is False


@pytest.mark.parametrize("contents", ["", None, 12345, []])
def test_unusable_contents_hold_no_block(contents):
    assert textblock.has_block(contents, BEGIN, END) is False


###########################################################
# Adding
###########################################################

def test_a_block_is_appended_to_an_existing_file():
    built = textblock.set_block("existing content\n", "body", BEGIN, END)

    assert built.startswith("existing content")
    assert BEGIN in built and END in built


def test_an_empty_file_becomes_just_the_block():
    built = textblock.set_block("", "body", BEGIN, END)

    assert built == "%s\nbody\n%s\n" % (BEGIN, END)


def test_a_body_given_as_lines_is_joined():
    built = textblock.set_block("", ["one", "two"], BEGIN, END)

    assert block_of(built) == "one\ntwo"


def test_a_note_sits_inside_the_block():
    built = textblock.set_block("", "body", BEGIN, END, note = NOTE)

    assert NOTE in built
    assert built.index(BEGIN) < built.index(NOTE) < built.index("body")


def test_a_note_is_not_part_of_the_body():
    built = textblock.set_block("", "body", BEGIN, END, note = NOTE)

    assert block_of(built) == "body"


def test_a_block_ends_with_a_newline():
    # A file whose last line is unterminated upsets several of the tools that
    # read these.
    assert textblock.set_block("", "body", BEGIN, END).endswith("\n")


def test_an_empty_body_still_produces_a_block():
    built = textblock.set_block("", "", BEGIN, END)

    assert textblock.has_block(built, BEGIN, END) is True


###########################################################
# Replacing
###########################################################

def test_a_second_update_replaces_rather_than_appends():
    once = textblock.set_block("existing\n", "first", BEGIN, END)
    twice = textblock.set_block(once, "second", BEGIN, END)

    assert twice.count(BEGIN) == 1
    assert block_of(twice) == "second"


def test_the_same_update_twice_changes_nothing():
    # The whole point: this runs on every setup.
    once = textblock.set_block("existing\n", "body", BEGIN, END)

    assert textblock.set_block(once, "body", BEGIN, END) == once


def test_content_before_the_block_is_kept():
    once = textblock.set_block("keep me\n", "first", BEGIN, END)
    twice = textblock.set_block(once, "second", BEGIN, END)

    assert twice.startswith("keep me")


def test_content_after_the_block_is_kept():
    contents = "before\n%s\nold\n%s\nafter\n" % (BEGIN, END)
    built = textblock.set_block(contents, "new", BEGIN, END)

    assert "after" in built
    assert "old" not in built


def test_a_user_edit_outside_the_block_survives():
    contents = "%s\nold\n%s\n\nmy own alias\n" % (BEGIN, END)
    built = textblock.set_block(contents, "new", BEGIN, END)

    assert "my own alias" in built


###########################################################
# Removing
###########################################################

def test_a_block_is_removed():
    contents = textblock.set_block("keep me\n", "body", BEGIN, END)
    built = textblock.remove_block(contents, BEGIN, END)

    assert BEGIN not in built
    assert "body" not in built


def test_removing_restores_the_original_content():
    original = "keep me\n\nand me\n"
    contents = textblock.set_block(original, "body", BEGIN, END)

    assert textblock.remove_block(contents, BEGIN, END).strip() == original.strip()


def test_removing_from_a_file_without_a_block_changes_nothing():
    original = "just content\n"

    assert textblock.remove_block(original, BEGIN, END) == original


def test_removing_the_only_content_leaves_an_empty_file():
    contents = textblock.set_block("", "body", BEGIN, END)

    assert textblock.remove_block(contents, BEGIN, END).strip() == ""


def test_removing_keeps_what_came_after():
    contents = "%s\nbody\n%s\nafter\n" % (BEGIN, END)
    built = textblock.remove_block(contents, BEGIN, END)

    assert built.strip() == "after"


def test_removing_twice_is_stable():
    contents = textblock.set_block("keep me\n", "body", BEGIN, END)
    once = textblock.remove_block(contents, BEGIN, END)

    assert textblock.remove_block(once, BEGIN, END) == once


@pytest.mark.parametrize("contents", [None, 12345])
def test_removing_from_unusable_contents_is_empty(contents):
    assert textblock.remove_block(contents, BEGIN, END) == ""


###########################################################
# Reading back
###########################################################

def test_a_body_round_trips():
    contents = textblock.set_block("before\n", "one\ntwo", BEGIN, END)

    assert block_of(contents) == "one\ntwo"


def test_a_body_round_trips_through_a_note():
    contents = textblock.set_block("before\n", "body", BEGIN, END, note = NOTE)

    assert block_of(contents) == "body"


def test_a_missing_block_reads_as_nothing():
    assert block_of("no block here\n") is None


def test_an_empty_body_reads_as_empty():
    contents = textblock.set_block("", "", BEGIN, END)

    assert block_of(contents) == ""


###########################################################
# Marker independence
###########################################################

@pytest.mark.parametrize("begin,end", [
    ("# BEGIN JoyBox local testing", "# END JoyBox local testing"),
    ("# >>> JOYBOX MANAGED BLOCK >>>", "# <<< JOYBOX MANAGED BLOCK <<<"),
    ("### start ###", "### stop ###"),
])
def test_any_marker_pair_works(begin, end):
    built = textblock.set_block("before\n", "body", begin, end)

    assert textblock.read_block_body(built, begin, end) == "body"
    assert textblock.remove_block(built, begin, end).strip() == "before"


def test_two_different_blocks_coexist_in_one_file():
    # /etc/hosts could hold a block from something else entirely.
    other_begin, other_end = "# BEGIN other", "# END other"
    contents = textblock.set_block("", "theirs", other_begin, other_end)
    contents = textblock.set_block(contents, "ours", BEGIN, END)

    assert textblock.read_block_body(contents, other_begin, other_end) == "theirs"
    assert textblock.read_block_body(contents, BEGIN, END) == "ours"


def test_removing_one_block_leaves_the_other():
    other_begin, other_end = "# BEGIN other", "# END other"
    contents = textblock.set_block("", "theirs", other_begin, other_end)
    contents = textblock.set_block(contents, "ours", BEGIN, END)
    built = textblock.remove_block(contents, BEGIN, END)

    assert textblock.read_block_body(built, other_begin, other_end) == "theirs"
    assert textblock.has_block(built, BEGIN, END) is False
