name: Security

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "17 6 * * 1"
  workflow_dispatch:

permissions: {}

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    name: Security
    uses: NearlyTRex/Workflows/.github/workflows/security.yml@c2daac4d6f891b24edb680b073710f4dcd7c9467 # v0.2.2
    permissions:
      contents: read

  codeql:
    name: CodeQL
    uses: NearlyTRex/Workflows/.github/workflows/codeql.yml@c2daac4d6f891b24edb680b073710f4dcd7c9467 # v0.2.2
    permissions:
      actions: read
      contents: read
      security-events: write
    with:
      languages: '["python", "actions"]'

  dependency-review:
    name: Dependency Review
    if: github.event_name == 'pull_request'
    uses: NearlyTRex/Workflows/.github/workflows/dependency-review.yml@c2daac4d6f891b24edb680b073710f4dcd7c9467 # v0.2.2
    permissions:
      contents: read
